import type { ComponentType } from "react";
import {
  ToolChill,
  ToolCloud,
  ToolHeat,
  ToolLightning,
  ToolPop,
  ToolShot,
} from "@/components/tools/air";
import {
  ToolCraftCare,
  ToolCraftFire,
  ToolCraftKnots,
  ToolCraftNatural,
  ToolCraftShelters,
  ToolCraftSignals,
  ToolCraftTraps,
} from "@/components/tools/bushcraft";
import {
  ToolAvpu,
  ToolBattery,
  ToolBoil,
  ToolBurns,
  ToolEqns,
  ToolExposure,
  ToolFuel,
  ToolGcs,
  ToolHang,
  ToolHeight,
  ToolHike,
  ToolCals,
  ToolLost,
  ToolMarch,
  ToolMist,
  ToolNeed,
  ToolPace,
  ToolPriorities,
  ToolPulse,
  ToolResp,
  ToolRiver,
  ToolRope,
  ToolShock,
  ToolSignal,
  ToolSlope,
  ToolStop,
  ToolVitals,
} from "@/components/tools/rest";

export const TOOLS: Record<string, ComponentType> = {
  pop: ToolPop,
  cloud: ToolCloud,
  heat: ToolHeat,
  chill: ToolChill,
  lightning: ToolLightning,
  shot: ToolShot,
  slope: ToolSlope,
  hike: ToolHike,
  cals: ToolCals,
  pace: ToolPace,
  height: ToolHeight,
  boil: ToolBoil,
  need: ToolNeed,
  river: ToolRiver,
  shelters: ToolCraftShelters,
  traps: ToolCraftTraps,
  knots: ToolCraftKnots,
  craftsig: ToolCraftSignals,
  fieldcare: ToolCraftCare,
  natural: ToolCraftNatural,
  firecraft: ToolCraftFire,
  rope: ToolRope,
  hang: ToolHang,
  battery: ToolBattery,
  fuel: ToolFuel,
  avpu: ToolAvpu,
  gcs: ToolGcs,
  pulse: ToolPulse,
  resp: ToolResp,
  march: ToolMarch,
  shock: ToolShock,
  burns: ToolBurns,
  mist: ToolMist,
  vitals: ToolVitals,
  exposure: ToolExposure,
  stop: ToolStop,
  priorities: ToolPriorities,
  signal: ToolSignal,
  lost: ToolLost,
  eqns: ToolEqns,
};
