/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallRouteImport } from './routes/install'
import { Route as MModuleIdRouteImport } from './routes/m.$moduleId'
import { Route as MModuleIdToolIdRouteImport } from './routes/m.$moduleId.$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleIdRoute = MModuleIdRouteImport.update({
  id: '/m/$moduleId',
  path: '/m/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleIdToolIdRoute = MModuleIdToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => MModuleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/m/$moduleId': typeof MModuleIdRouteWithChildren
  '/m/$moduleId/$toolId': typeof MModuleIdToolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/m/$moduleId': typeof MModuleIdRouteWithChildren
  '/m/$moduleId/$toolId': typeof MModuleIdToolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/m/$moduleId': typeof MModuleIdRouteWithChildren
  '/m/$moduleId/$toolId': typeof MModuleIdToolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/install' | '/m/$moduleId' | '/m/$moduleId/$toolId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/install' | '/m/$moduleId' | '/m/$moduleId/$toolId'
  id: '__root__' | '/' | '/install' | '/m/$moduleId' | '/m/$moduleId/$toolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRoute: typeof InstallRoute
  MModuleIdRoute: typeof MModuleIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$moduleId': {
      id: '/m/$moduleId'
      path: '/m/$moduleId'
      fullPath: '/m/$moduleId'
      preLoaderRoute: typeof MModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$moduleId/$toolId': {
      id: '/m/$moduleId/$toolId'
      path: '/$toolId'
      fullPath: '/m/$moduleId/$toolId'
      preLoaderRoute: typeof MModuleIdToolIdRouteImport
      parentRoute: typeof MModuleIdRoute
    }
  }
}

interface MModuleIdRouteChildren {
  MModuleIdToolIdRoute: typeof MModuleIdToolIdRoute
}

const MModuleIdRouteChildren: MModuleIdRouteChildren = {
  MModuleIdToolIdRoute: MModuleIdToolIdRoute,
}

const MModuleIdRouteWithChildren = MModuleIdRoute._addFileChildren(
  MModuleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRoute: InstallRoute,
  MModuleIdRoute: MModuleIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
